server:
  port: 9081
  servlet:
    context-path: /
spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  profiles:
    active: druid
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 150MB
  resources:
    static-locations:
      - classpath:/static/
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
  datasource:
    druid:
      initialSize:  5
      #最小连接池数量
      minIdle:  10
      #最大连接池数量
      maxActive:  20
      #配置获取连接等待超时的时间
      maxWait:  60000
      #配置检测的间隔时间，检测时需要关闭空闲的连接，单位为毫秒
      timeBetweenEvictionRunsMillis:  60000
      #配置连接池最小的生命周期,单位毫秒
      minEvictableIdleTimeMillis: 300000
      #配置连接池最大的生命周期，单位毫秒
      maxEvictableIdleTimeMillis: 900000
      #配置检测连接是否有效
      validationQuery:  SELECT 1
      testWhileIdle:  true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled:  true
      statViewServlet:
        enabled:  true
        #设置白名单，不填写则允许所有访问
        allow:
        url-pattern: /admin/druid/*
      filter:
        stat:
          enabled:  true
          #慢SQL记录
          log-slow-sql: true
          slow-sql-millis:  1000
          merge-sql:  true
        wall:
          config:
            multi-statement-allow:  true
# 日志打印
logging:
  config: classpath:logback-spring.xml
  file:
    path: appdate/logs/